baseURL = "https://www.fantasycourt.nl"
languageCode = "nl-nl"
DefaultContentLanguage = "nl"
title = "Fantasy Court Website"
theme = "fantasy-court"

# We're not using taxonomies
disableKinds = ["taxonomy", "term"]

# Default image that shows up at the top of pages
[params.header-image]
url = "/images/FC_tournament.jpg"
alt = "Fantasy Court Swordfighting Tournament"
position-x = "50%"
position-y = "45%"

# Open Graph
[params.og]
locale = 'nl_NL' # Hugo's languageCode is in a different format and is not supported by OG
site-name = "Fantasy Court"
title = "Fantasy Court"
description = "Fantasy Court is een fantasy festival dat zich focust op de unieke en niche cultuur rondom fantasy-evenementen en LARP (Live Action Roleplay)."
image = "/images/icons/Fantasy Court - Logo.png"
image-alt = "Fantasy Court Logo"

# Languages
[languages]
[languages.nl]
name = "Nederlands"
title = "Fantasy Court"
weight = 1

[[languages.nl.menu.main]]
identifier = "welcome"
title = "Welkom"
url = "/"
weight = 2

[[languages.nl.menu.main]]
identifier = "practical"
title = "Praktische Info"
url = "/praktische_info/"
weight = 3

[[languages.nl.menu.main]]
identifier = "general"
parent = "practical"
title = "Bezoekersinformatie"
url = "/praktische_info/algemeen/"
weight = 1

[[languages.nl.menu.main]]
identifier = "sfeerimpressie"
parent = "practical"
title = "sfeerimpressie"
url = "/praktische_info/sfeerimpressie/"
weight = 2


[[languages.nl.menu.main]]
identifier = "registration"
parent = "practical"
title = "Aanmelding Standhouders"
url = "/praktische_info/aanmelden/"
weight = 3

[[languages.nl.menu.main]]
identifier = "FAQ"
parent = "practical"
title = "FAQ"
url = "/praktische_info/faq/"
weight = 4

[[languages.nl.menu.main]]
identifier = "programma"
title = "Programma"
url = "/programma_2025/"
weight = 4

[[languages.nl.menu.main]]
identifier = "Performers"
parent = "programma"
title = "Artiesten"
url = "/programma_2025/artiesten/"
weight = 1

[[languages.nl.menu.main]]
identifier = "Activities"
parent = "programma"
title = "Activiteiten"
url = "/programma_2025/activiteiten/"
weight = 2

[[languages.nl.menu.main]]
identifier = "Vendors"
parent = "programma"
title = "Kramen- Standhouders"
url = "/programma_2025/kramen/"
weight = 3

[[languages.nl.menu.main]]
identifier = "news"
title = "Nieuwsarchief"
url = "/nieuws/"
weight = 5

[[languages.nl.menu.main]]
identifier = "previous"
title = "Vorige Edities"
url = "/vorige_edities/"
weight = 6

[languages.en]
name = "English"
title = "Fantasy Court"
weight = 1
languageCode = "en-gb"

[languages.en.og]
locale = "en_GB"
description = "Fantasy Court is a fantasy festival that is focused on the somewhat unique and niche culture that surrounds fantasy events and LARP (Live Action Role Playing)."
# copy of above
  # If this is omitted, then hugo uses the empty string for these values.
  # The docs indicate it should just use the top-level params, but those values aren't
  #   even avaible in $.Site.Parms in the first place... WHY!?
  site-name = "Fantasy Court"
  title = "Fantasy Court"
  image = "/images/icons/Fantasy Court - Logo.png"
  image-alt = "Fantasy Court Logo"
# end copy


[[languages.en.menu.main]]
identifier = "welcome"
title = "Welcome"
url = "/"
weight = 2

[[languages.en.menu.main]]
identifier = "practical"
title = "Practical Information"
url = "/praktische_info/"
weight = 3


[[languages.en.menu.main]]
identifier = "general"
parent = "practical"
title = "Visitor Information"
url = "/praktische_info/algemeen/"
weight = 1

[[languages.nl.menu.main]]
identifier = "sfeerimpressie"
parent = "practical"
title = "Impression"
url = "/praktische_info/sfeerimpressie/"
weight = 2

[[languages.en.menu.main]]
identifier = "registration"
parent = "practical"
title = "Registration Vendors"
url = "/praktische_info/aanmelden/"
weight = 3

[[languages.en.menu.main]]
identifier = "FAQ"
parent = "practical"
title = "FAQ"
url = "/praktische_info/faq/"
weight = 4

[[languages.en.menu.main]]
identifier = "programma"
title = "Programme"
url = "/programma_2025/"
weight = 4

[[languages.en.menu.main]]
identifier = "Performers"
parent = "programma"
title = "Performers"
url = "/programma_2025/artiesten/"
weight = 1

[[languages.en.menu.main]]
identifier = "Activities"
parent = "programma"
title = "Activities"
url = "/programma_2025/activiteiten/"
weight = 2

[[languages.en.menu.main]]
identifier = "Vendors"
parent = "programma"
title = "Vendors"
url = "/programma_2025/kramen/"
weight = 3

[[languages.en.menu.main]]
identifier = "news"
title = "News Archive"
url = "/news/"
weight = 5

[[languages.en.menu.main]]
identifier = "previous"
title = "Previous Editions"
url = "/vorige_edities/"
weight = 6

# Determine frontmatter order
[frontmatter]
# Look for the file's date in the filename first, only then in the frontmatter (date, publishdate, lastmod)
date = [":filename", ":default"]

# TODO
[[cascade]]
  [cascade._build]
    list = 'local'
    publishResources = false
    render = 'never'
  [cascade._target]
    kind = 'page'
    path = '/news/**'


# Privacy settings
[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false
  [privacy.vimeo]
    disable = false
    enableDNT = true
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
